# Generated by Django 5.2.5 on 2025-08-31 15:32

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.picture'),
        ),
        migrations.AddField(
            model_name='picturetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shop.picture'),
        ),
        migrations.AlterUniqueTogether(
            name='picturetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
