# Generated by Django 5.2.5 on 2025-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
