# Generated by Django 5.2.5 on 2025-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_picture_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturetranslation',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
