# Generated by Django 5.2.5 on 2025-09-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_picturetranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirmation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
