# Generated by Django 5.2.5 on 2025-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inMailingList',
        ),
        migrations.AddField(
            model_name='user',
            name='cartList',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favouritesList',
            field=models.JSONField(default=list, null=True),
        ),
    ]
